parameters:
- name: IsProd
  type: boolean
  default: false
jobs:
- job: Phase_1
  displayName: Phase 1
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 1
  variables:
  - name: ArchiveSymbols
    value: "$(TAfBTArchiveSymbols)"
  - name: BuildConfiguration
    value: "$(TAfBTBuildConfiguration)"
  - name: BuildPlatform
    value: Any CPU
  - name: CodeQL.Enabled
    value: True
  - name: Codeql.Language
    value: csharp,cpp
  - name: CodeQL.TSAEnabled
    value: True
  - name: Codeql.TSAOptionsPath
    value: $(Build.SourcesDirectory)\vs-boost-unit-test-adapter\TSAOptions.json
  - name: DropRoot
    value: '\\cpvsbuild\drops'
  - name: Packaging.EnableSBOMSigning
    value: "$(TAfBTEnableSBOMSigning)"
  - name: ProductComponent
    value: "$(TAfBTProductComponent)"
  - name: Publish
    value: "$(TAfBTPublish)"
  # Quick build is used to skip some compliance tasks to quickly generate a .vsix for testing.
  - name: RunAdditionalComplianceChecks
    value: "$(TAfBTRunAdditionalComplianceChecks)"
  - name: TAfBTRealSign
    value: "$(RealSign)"
  - name: RetainBuild
    value: "$(TAfBTRetainBuild)"
  - name: TeamName
    value: VCLS
  - name: VersionNumber
    value: "$(TAfBTVersionNumber)"
  templateContext:
    outputs:
    - output: pipelineArtifact
      displayName: 'Publish Artifact: drop'
      condition: eq('${{ parameters.IsProd }}', true)
      targetPath: $(Build.ArtifactStagingDirectory)\drop
      artifactName: drop
    mb:
      signing:
        enabled: true
        ${{ if eq(parameters.IsProd, true) }}:
          signType: 'real'
          signWithProd: true
        ${{ else }}:
          signType: 'test'
        zipSources: false
      localization:
        enabled: true
  steps:
  - checkout: self
    displayName: 'Checkout vs-boost-unit-test-adapter Git Repo'
    clean: true
    fetchDepth: 1
    persistCredentials: true
  - checkout: VCLS-Extensions
    displayName: 'Checkout VCLS-Extensions ADO Repo to copy public key'
    clean: true
    fetchDepth: 1
    persistCredentials: true
  # After checking out the vs-boost-unit-test-adapter repo copy all files up one directory to avoid having to change all paths in scripts.
  - task: CopyFiles@2
    displayName: 'Copy vs-boost-unit-test-adapter Files to: $(Build.SourcesDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\vs-boost-unit-test-adapter'
      TargetFolder: '$(Build.SourcesDirectory)'
  - task: NuGetToolInstaller@1
    displayName: Install NuGet
    inputs:
      versionSpec: 5.9.1
  - task: ms-vseng.MicroBuildTasks.32f78468-e895-4f47-962c-58a699361df8.MicroBuildSwixPlugin@4
    displayName: Install Swix Plugin
  # Have to use manual CodeQL Init task for now because the 1ES template auto injected CodeQL contains bug that hangs during pipeline builds.
  - task: MS-CST-E.codeql-3000-release.init-task.CodeQL3000Init@0
    displayName: CodeQL 3000 Init
  - task: PowerShell@2
    displayName: Set Version
    inputs:
      targetType: filePath
      filePath: './SetVersion.ps1'
      arguments: '-version $(VersionNumber)'
  - task: CopyFiles@2
    displayName: 'Copy FinalPublicKey.snk to vs-boost-unit-test-adapter'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/VCLS-Extensions/InternalAPIs/DevDiv'
      Contents: 'FinalPublicKey.snk'
      TargetFolder: '$(Build.SourcesDirectory)'
  - task: PowerShell@1
    displayName: Add Keys for RealSign to TAfBT
    condition: eq('${{ parameters.IsProd }}', true)
    inputs:
      scriptType: inlineScript
      inlineScript: |-
        $projects_to_sign = @(
          "Antlr.DOT\Antlr.DOT.csproj",
          "BoostTestAdapter\BoostTestAdapter.csproj",
          "BoostTestPackage\BoostTestPackage.csproj",
          "BoostTestPlugin\BoostTestPlugin.csproj",
          "BoostTestShared\BoostTestShared.csproj",
          "ThirdPartySigning\ThirdPartySigning.csproj",
          "VisualStudioAdapter\VisualStudioAdapter.csproj"
        )
        $projects_to_sign | ForEach-Object {
          $xml = [xml](Get-Content $_)
          $KeyFile = $xml.CreateElement("AssemblyOriginatorKeyFile", "http://schemas.microsoft.com/developer/msbuild/2003")
          $KeyFile.set_InnerXML("`$(EnlistmentRoot)FinalPublicKey.snk")
          $xml | ForEach-Object { $_.Project.PropertyGroup | ForEach-Object { if ($_.Condition -like '*(RealSign)'' == ''True''') { $_.AppendChild($KeyFile) } } }
          $xml.Save("$pwd\$_")
        }
  - task: NuGetCommand@2
    displayName: NuGet restore for ThirdPartySigning and MicroBuild.Core
    inputs:
      solution: swix/packages.config
      selectOrConfig: config
      nugetConfigPath: NuGet.config
      noCache: true
      packagesDirectory: NuGetPackages
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: BoostTestAdapter.sln
      selectOrConfig: config
      nugetConfigPath: NuGet.config
      noCache: true
  - task: VSBuild@1
    displayName: Build solution BoostTestAdapter.sln
    inputs:
      solution: BoostTestAdapter.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true
      createLogFile: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\drop'
    inputs:
      Contents: '**\out\binaries\**'
      TargetFolder: $(Build.ArtifactStagingDirectory)\drop
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Manifest Generator '
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)\drop'
      PackageName: 'Test Adapter for Boost.Test'
      PackageVersion: 1.1.0.4
  - task: NuGetCommand@2
    displayName: NuGet restore for vsmanproj
    inputs:
      solution: swix/packages.config
      selectOrConfig: config
      nugetConfigPath: NuGet.config
      noCache: true
      packagesDirectory: ..\NugetPackages
    continueOnError: true
  - task: VSBuild@1
    displayName: Build vsmanproj
    condition: and(succeeded(), eq(variables['ProductComponent'], true))
    inputs:
      solution: swix/Microsoft.VisualStudio.VC.Ide.TestAdapterForBoostTest.vsmanproj
      msbuildArgs: /p:ArtifactsDir=$(Build.ArtifactStagingDirectory)
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: CopyFiles@2
    displayName: Copy setup files to drop root
    inputs:
      SourceFolder: out\binaries\$(BuildConfiguration)\Microsoft.VisualStudio.VC.Ide.TestAdapterForBoostTest
      Contents: '*'
      TargetFolder: $(Build.ArtifactStagingDirectory)\drop
    continueOnError: true
  - task: CopyFiles@2
    displayName: Copy vsix to root
    inputs:
      SourceFolder: out\binaries\$(BuildConfiguration)\BoostTestPlugin
      Contents: BoostUnitTestAdapter.vsix
      TargetFolder: $(Build.ArtifactStagingDirectory)\drop
    continueOnError: true
  # Pull a list only of files we build and ship to be scanned in drop/FilesToScanDrop.
  - task: PowerShell@2
    displayName: 'Copy Scannable Files to: $(Build.ArtifactStagingDirectory)\drop\FilesToScanDrop'
    inputs:
      filePath: './FilesToScan.ps1'
      arguments: '-buildArtifactStagingDirectory $(Build.ArtifactStagingDirectory)\drop -directoryToSearch $(Build.ArtifactStagingDirectory)\drop'
  # This is a time-consuming compliance task, so if we want to run a quick build (off by default), then we skip this task.
  - task: SDLNativeRules@3
    displayName: 'Run the PREfast SDL Native Rules for MSBuild'
    condition: eq (variables.RunAdditionalComplianceChecks, True)
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      publishXML: true
      userProvideBuildInfo: auto
      rulesetName: Recommended
      setupCommandlinePicker: 'vs2022'
  # This is a time-consuming compliance task, so if we want to run a quick build (off by default), then we skip this task.
  - task: PoliCheck@2
    displayName: 'PoliCheck on vs-boost-unit-test-adapter repo'
    condition: eq (variables.RunAdditionalComplianceChecks, True)
    inputs:
      targetType: 'F'
      targetArgument: '$(Build.SourcesDirectory)/vs-boost-unit-test-adapter'
  # This is a time-consuming compliance task, so if we want to run a quick build (off by default), then we skip this task.
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-apiscan.APIScan@2
    displayName: 'Run APIScan'
    condition: eq (variables.RunAdditionalComplianceChecks, True)
    inputs:
      azureSubscription: 'VSEng-APIScanSC'
      softwareFolder: '$(Build.ArtifactStagingDirectory)\drop\FilesToScanDrop'
      softwareName: BoostTest
      softwareVersionNum: 1.0
      isLargeApp: false
      toolVersion: 'Latest'
      verbosityLevel: silent
      continueOnError: true
    env:
      AzureServicesAuthConnectionString: RunAs=App;AppId=d318cba7-db4d-4fb3-99e1-01879cb74e91;TenantId=72f988bf-86f1-41af-91ab-2d7cd011db47;ServiceConnectionId=93e24264-c5e6-4681-8175-ec8a41668480;
  # Have to use manual CodeQL Init task for now because the 1ES template auto injected CodeQL contains bug that hangs during pipeline builds.
  - task: MS-CST-E.codeql-3000-release.finalize-task.CodeQL3000Finalize@0
    displayName: CodeQL 3000 Finalize
  # This is a time-consuming compliance task, so if we want to run a quick build (off by default), then we skip this task.
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@3
    displayName: 'Publish Guardian Artifacts'
    condition: eq (variables.RunAdditionalComplianceChecks, True)
    inputs:
      PublishProcessedResults: true
    continueOnError: true
  - task: 1ES.MicroBuildVstsDrop@1
    displayName: Upload VSTS Drop
    condition: eq('${{ parameters.IsProd }}', true)
    inputs:
      dropFolder: $(Build.ArtifactStagingDirectory)\drop
      dropName: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
      accessToken: $(System.AccessToken)
      dropServiceUri: https://devdiv.artifacts.visualstudio.com/DefaultCollection
      vsDropServiceUri: "https://vsdrop.corp.microsoft.com/file/v1"
  - task: ms-vseng.MicroBuildShipTasks.4a4e1dc3-01d0-484f-94ac-f918aaf7d509.MicroBuildRetainVstsDrops@1
    displayName: Retain VSTS Drops
    condition: and(succeeded(), eq(variables['RetainBuild'], true), eq('${{ parameters.IsProd }}', true))
    inputs:
      DropNames: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
      AccessToken: $(System.AccessToken)
      DropServiceUri: https://devdiv.artifacts.visualstudio.com/DefaultCollection
  - task: PublishSymbols@2
    displayName: 'Enable Source Server'
    condition: eq('${{ parameters.IsProd }}', true)
    inputs:
      SearchPattern: 'out\binaries\**\*.pdb'
      # We use the MicroBuild Archive Symbols task so we need to publish the symbols here.
      # See the following for more info: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/34299/Handling-Symbols
      PublishSymbols: false
    continueOnError: true
  - task: ms-vseng.MicroBuildShipTasks.0ffdda1d-8c7b-40da-b8b1-061660eaeea3.MicroBuildArchiveSymbols@6
    displayName: 'Archive TestAdapterForBoostTest on Symweb'
    condition: and(eq (variables.ArchiveSymbols, True), eq('${{ parameters.IsProd }}', true))
    inputs:
      azureSubscription: 'VSEng-SymbolsUpload'
      SymbolsFeatureName: TestAdapterForBoostTest
      SymbolsProject: VS
      SymbolsAgentPath: '$(Build.ArtifactStagingDirectory)\drop'
  - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
    displayName: 'Send Telemetry'
    condition: and(eq (variables.ArchiveSymbols, True), eq('${{ parameters.IsProd }}', true))
  - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
    displayName: Perform Cleanup Tasks
    condition: always()