//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoostTestAdapter {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoostTestAdapter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   File {0} came from another computer and was blocked to help protect this computer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BadFileZone {
            get {
                return ResourceManager.GetString("BadFileZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception caught while running test batch {0} [{1}] ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BatchException {
            get {
                return ResourceManager.GetString("BatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No valid test batching strategy was found. Tests skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BatchStrategyNotFound {
            get {
                return ResourceManager.GetString("BatchStrategyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No valid test batching strategy was found for {0}. Source skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BatchStrategyNotFoundFor {
            get {
                return ResourceManager.GetString("BatchStrategyNotFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CmdLine arguments: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdLineArguments {
            get {
                return ResourceManager.GetString("CmdLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create a DBGHELP instance for &apos;{0}&apos; to determine whether symbols are available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldNotCreateDbgHelp {
            get {
                return ResourceManager.GetString("CouldNotCreateDbgHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not locate symbols for &apos;{0}&apos;. To make use of &apos;--list_content&apos; discovery, ensure that symbols are available or make use of &apos;&lt;ForceListContent&gt;&apos; via a .runsettings file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldNotLocateDebugSymbols {
            get {
                return ResourceManager.GetString("CouldNotLocateDebugSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debugging:   -&gt; [{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Debugging {
            get {
                return ResourceManager.GetString("Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not obtain debugging properties for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebuggingPropertiesNotFound {
            get {
                return ResourceManager.GetString("DebuggingPropertiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discovering ({0}):   -&gt; [{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Discovering {
            get {
                return ResourceManager.GetString("Discovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception caught while discovering tests: {0} ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiscoveryException {
            get {
                return ResourceManager.GetString("DiscoveryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception caught while discovering tests for {0} ({1} - {2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiscoveryExceptionFor {
            get {
                return ResourceManager.GetString("DiscoveryExceptionFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception: {0} ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executing:   -&gt; [{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No suitable executor found for [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExecutorNotFound {
            get {
                return ResourceManager.GetString("ExecutorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process could not be added to Job Object. Test process may end up orphaned on abrupt closure. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToAddProcess {
            get {
                return ResourceManager.GetString("FailedToAddProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to terminate process {0}. Process may still be running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToTerminateProcess {
            get {
                return ResourceManager.GetString("FailedToTerminateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File {0} does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finding processes spawned by process with Id [{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FindingChildren {
            get {
                return ResourceManager.GetString("FindingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found test: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FoundTest {
            get {
                return ResourceManager.GetString("FoundTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageDirectoryEntryToData failed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageDirectoryEntryToData {
            get {
                return ResourceManager.GetString("ImageDirectoryEntryToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid file defining property under {0}. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPropertyFile {
            get {
                return ResourceManager.GetString("InvalidPropertyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --list_content=DOT for {0} failed with exit code {1}. Skipping. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListContentProcessFailure {
            get {
                return ResourceManager.GetString("ListContentProcessFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   list_content file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListContentsFile {
            get {
                return ResourceManager.GetString("ListContentsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --list_content=DOT output for {0} is not available. Skipping. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListContentsNotFound {
            get {
                return ResourceManager.GetString("ListContentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log file         : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logger initialized. Logging to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoggerInitialized {
            get {
                return ResourceManager.GetString("LoggerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child process [{0}] does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative Paths are being used. Please note that test navigation from the Test Explorer window will not be available. To enable such functionality, the Use Full Paths setting under C++ -&gt; Advanced in the project&apos;s Property Page must be set to Yes (/FC). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RelativePathsInUse {
            get {
                return ResourceManager.GetString("RelativePathsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to extract test report from standard error [{0}] to report file [{1}] ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportException {
            get {
                return ResourceManager.GetString("ReportException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report file      : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportFile {
            get {
                return ResourceManager.GetString("ReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value of the &apos;path&apos; argument is a reserved keyword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReservedPath {
            get {
                return ResourceManager.GetString("ReservedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boost Test result file was not found or is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResultFileNotFound {
            get {
                return ResourceManager.GetString("ResultFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Boost Test Runner exceeded the timeout threshold of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunnerTimeout {
            get {
                return ResourceManager.GetString("RunnerTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StdErr file      : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StdErrFile {
            get {
                return ResourceManager.GetString("StdErrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StdOut file      : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StdOutFile {
            get {
                return ResourceManager.GetString("StdOutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception caught while trying to delete temporary file [{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TempDeleteException {
            get {
                return ResourceManager.GetString("TempDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully terminated process {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TerminatedProcess {
            get {
                return ResourceManager.GetString("TerminatedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception caught while running tests from {0} ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestException {
            get {
                return ResourceManager.GetString("TestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test setup error: no test cases matching filter (test name contains commas) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestNameContainsCommas {
            get {
                return ResourceManager.GetString("TestNameContainsCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test setup error: no test cases matching filter (test name contains spaces) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestNameContainsSpaces {
            get {
                return ResourceManager.GetString("TestNameContainsSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test setup error: no test cases matching filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestNotFound {
            get {
                return ResourceManager.GetString("TestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout exceeded. Test ran for more than {0} ms. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set information. Error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnableToSetInformation {
            get {
                return ResourceManager.GetString("UnableToSetInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnMapAndLoad failed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnMapLoad {
            get {
                return ResourceManager.GetString("UnMapLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working directory: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve WorkingDirectory from Visual Studio configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WorkingDirectoryNotFound {
            get {
                return ResourceManager.GetString("WorkingDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve WorkingDirectory from Visual Studio configuration: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WorkingDirectoryNotFoundEx {
            get {
                return ResourceManager.GetString("WorkingDirectoryNotFoundEx", resourceCulture);
            }
        }
    }
}
